export const dom = {
  playerGold: document.getElementById('playerGold'),
  playerGoldIncome: document.getElementById('playerGoldIncome'),
  playerGoldScore: document.getElementById('playerGoldScore'),
  playerGoldIncomeScore: document.getElementById('playerGoldIncomeScore'),
  playerTroops: document.getElementById('playerTroops'),
  playerCells: document.getElementById('playerCells'),
  playerGrowth: document.getElementById('playerGrowth'),
  leaderboardEntries: document.getElementById('leaderboardEntries'),
  rangeValue: document.getElementById('rangeValue'),
  spawnTimer: document.getElementById('spawnTimer'),
  playerMax: document.getElementById('playerMax'),
  playerEnCamp: document.getElementById('playerEnCamp'),
  playerFactionTitle: document.getElementById('playerFactionTitle'),
  btnFactory: document.getElementById('btn-factory'),
  btnCity: document.getElementById('btn-city'),
  btnDefense: document.getElementById('btn-defense'),
  btnSilo: document.getElementById('btn-silo'),
  btnMissile: document.getElementById('btn-missile'),
  btnPort: document.getElementById('btn-port'),
  btnArtillery: document.getElementById('btn-artillery'),
  costFactory: document.getElementById('cost-factory'),
  costCity: document.getElementById('cost-city'),
  costDefense: document.getElementById('cost-defense'),
  costSilo: document.getElementById('cost-silo'),
  costMissile: document.getElementById('cost-missile'),
  costPort: document.getElementById('cost-port'),
  costArtillery: document.getElementById('cost-artillery'),
  siloUpgradePanel: document.getElementById('siloUpgradePanel'),
  btnUpgradeSiloAction: document.getElementById('btn-upgrade-silo-action'),
  btnCloseSiloDetails: document.getElementById('btn-close-silo-details'),
  attackRange: document.getElementById('attackRange'),
  allianceModal: document.getElementById('allianceModal'),
  closeAllianceBtn: document.getElementById('closeAllianceBtn'),
  allianceCurrentStatus: document.getElementById('allianceCurrentStatus'),
  alliancePlayersList: document.getElementById('alliancePlayersList'),
  allianceProposalModal: document.getElementById('allianceProposalModal'),
  allianceProposalText: document.getElementById('allianceProposalText'),
  btnAcceptAlliance: document.getElementById('btnAcceptAlliance'),
  btnRejectAlliance: document.getElementById('btnRejectAlliance'),
  radialMenu: document.getElementById('radialMenu'),
};

export const canvas = document.getElementById('gameCanvas');
export const ctx = canvas ? canvas.getContext('2d') : null;
